version: '3.8'
services:
  php-apache-environment:
      container_name: php-apache
      build:
          context: ./docker
          dockerfile: Dockerfile
      depends_on:
        db:
          condition: service_healthy
      volumes:
          - .:/var/www/html/
      networks:
        - local-network
      ports:
          - 8000:80
  db:
      container_name: db
      image: mysql
      restart: unless-stopped
      environment:
          MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
          MYSQL_DATABASE: ${DATABASE}
          MYSQL_USER: ${NAME}
          MYSQL_PASSWORD: ${PASS}
      volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      networks:
        - local-network
      ports:
          - "9906:3306"
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 30s
        timeout: 10s
        retries: 5
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        db:
          condition: service_healthy
    networks:
      - local-network
    
networks:
  local-network:
    driver: bridge